version: "3.8"

services:
  backend:
    image: neeraj46665/ecommerce-backend:latest
    container_name: ecommerce-backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - MONGO_URI=mongodb://ecommerce-mongo:27017/ecommerce  # Hardcoded URL
      - JWT_SECRET=${JWT_SECRET}  # Dynamic secret
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}  # Dynamic secret
    depends_on:
      - mongo

  frontend:
    image: neeraj46665/ecommerce-frontend:latest
    container_name: ecommerce-frontend
    restart: always
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://localhost:4000  # Hardcoded URL
    depends_on:
      - backend

  mongo:
    image: mongo:6.0
    container_name: ecommerce-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
