name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Trigger on push to main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Build and push backend Docker image
      - name: Build and push backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ecommerce-backend:latest

      # Build and push frontend Docker image
      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ecommerce-frontend:latest

      # Deploy to EC2 via SSH
      # - name: Deploy to EC2
      #   uses: appleboy/ssh-action@v0.1.4
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USER }}
      #     key: ${{ secrets.EC2_SSH_KEY }}
      #     port: 22
      #     script: |
      #       # Install Docker Compose if not installed
      #       if ! command -v docker-compose &> /dev/null
      #       then
      #         sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      #         sudo chmod +x /usr/local/bin/docker-compose
      #       fi

      #       # Navigate to project directory
      #       cd ~/ecommerce || mkdir ~/ecommerce && cd ~/ecommerce

      #       # Create docker-compose.yml if not exists
      #       # (Assuming docker-compose.yml is part of the repository; alternatively, you can pull from Git)

      #       # Pull latest images
      #       docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/ecommerce-backend:latest
      #       docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/ecommerce-frontend:latest

      #       # Stop existing containers
      #       docker-compose down

      #       # Start containers with updated images
      #       docker-compose up -d --build

      #       # Optionally, you can run migrations or other setup tasks here
